name: Linting

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Linting Tools
      run: |
        python -m pip install --upgrade pip
        pip install --user pylint==2.6.0
        pip install --user black~=22.3
        pip install --user flake8~=4.0

    - name: Analysing the code with pylint
      run: |
        python -m pylint -E tooling/

    - name: Checking format with Black
      run: |
        python -m black --check tooling/

    - name: Checking format with Flake8
      run: |
        python -m flake8 tooling/

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install PyTest
      run: |
        pip install pytest
    - name: Run PyTest
      run: |
        pytest --junitxml=test-results/junit.xml tooling/

